#!/bin/sh
    SELF=$(readlink -f "$0")
    HERE=${SELF%/*}
    export SUSCAN_CONFIG_PATH="${HERE}/share/suscan/config"
    export LD_LIBRARY_PATH="${HERE}/lib:$LD_LIBRARY_PATH"
    exec "${HERE}"/bin/SigDigger "$@"
